#!/bin/sh

_pkgver=6.0.2
_pkgrel=1
source="https://github.com/pi-hole/web/archive/v$_pkgver.tar.gz"
dira="web-$_pkgver"
dirb="$dira.cust"

_ssc="/tmp/sedcontrol"

[[ -d $dira ]] && rm -r $dira
[[ -d $dirb ]] && rm -r $dirb

wget -q -nc -O admin-$_pkgver.tar.gz $source
tar xf admin-$_pkgver.tar.gz
cp -a $dira $dirb



# web admin footer update setup
sed -i "s|https:\/\/github.com\/pi-hole\/pi-hole\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-core|w $_ssc" "$dirb"/scripts/js/footer.js
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 1" && exit 1 ; fi
sed -i "s|https:\/\/github.com\/pi-hole\/FTL\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-ftl|w $_ssc" "$dirb"/scripts/js/footer.js
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 2" && exit 1 ; fi
sed -i "s|https:\/\/github.com\/pi-hole\/web\/releases|https:\/\/aur.archlinux.org\/packages\/pi-hole-web|w $_ssc" "$dirb"/scripts/js/footer.js
if [ -s $_ssc ] ; then rm $_ssc ; else echo "   ==> Sed error: web admin footer update setup 3" && exit 1 ; fi

# -----------------


diff -uprN $dira $dirb > arch-web-$_pkgver-$_pkgrel.patch

git add arch-web-$_pkgver-$_pkgrel.patch
git add patchgen
